exports.ATTACHMENT_RECORD_MODULE_ID_ADMIN = 1
exports.ATTACHMENT_RECORD_MODULE_ID_PRODCATEGORY = 2
exports.ATTACHMENT_RECORD_MODULE_ID_PRODTAGS = 3
exports.ATTACHMENT_RECORD_MODULE_ID_BRANDS = 4;
exports.ATTACHMENT_RECORD_MODULE_ID_PRODUCTS = 5